version: "3.7"

services:
  mongo:
    image: mongo:7.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - db:/data/db
  api:
    depends_on:
      - mongo
    build: ./api
    env_file: ./.env
    ports:
      - 3000:80
    volumes:
      - ./api:/app
      - node_modules:/api/node_modules

volumes:
  db:
  node_modules:
