version: "3.7"

services:
  mongo:
    image: mongo:7.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - db:/data/db
  api:
    depends_on:
      - mongo
    build: ./api
    env_file: ./.env
    ports:
      - 3000:80
    volumes:
      - ./api:/app
      - node_modules_api:/app/node_modules
  front:
    depends_on:
      - api
    build: ./spa
    ports:
      - 3080:3000
    volumes:
      - ./spa:/app
      - node_modules_front:/app/node_modules
  php:
    depends_on:
      - api
    image: php:fpm
    environment:
      API_URL: "http://api:80"
    volumes:
      - ./web:/app
  web:
    depends_on:
      - php
    image: nginx
    ports:
      - "3380:80"
    volumes:
      - ./web:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db:
  node_modules_api:
  node_modules_front:
